query L3Vpn($name: String!) {
  ServiceL3Vpn(name__value: $name) {
    edges {
      node {
        id
        name { value }
        vpn_id { value }
        address_family { value }
        status { value }
        tenant { node { id name { value } } }
        sites {
          edges {
            node {
              id
              name { value }
              routing_protocol { value }
              bgp_peer_asn { value }
              static_routes { value }
              status { value }
              pe_device {
                node {
                  id
                  name { value }
                  platform { node { name { value } } }
                  location {
                    node {
                      id
                      ... on LocationGeneric {
                        name { value }
                      }
                      ... on LocationSite {
                        name { value }
                      }
                    }
                  }
                }
              }
              customer_subnet { node { id prefix { value } } }
            }
          }
        }
      }
    }
  }
  LocationRegion {
    edges {
      node {
        id
        name { value }
      }
    }
  }
  LocationSite {
    edges {
      node {
        id
        name { value }
        parent {
          node {
            id
          }
        }
      }
    }
  }
  RoutingAutonomousSystem {
    edges {
      node {
        id
        asn { value }
        location {
          node {
            id
            ... on LocationGeneric {
              name { value }
            }
            ... on LocationSite {
              name { value }
            }
          }
        }
      }
    }
  }
}
