---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: LocationRegion
  data:
    - name: AMER
      shortname: amer
      description: AMER region covering the American hub offices.

---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: LocationSite
  data:
    - name: Raleigh
      shortname: rdu
      description: Raleigh - AMER hub; RTP primary market access.
      parent: amer

---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: LocationSite
  data:
    - name: Research Triangle Park
      shortname: rtp
      description: Research Triangle Park - AMER hub; RTP primary market access.
      parent: rdu