---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: RoutingAutonomousSystem
  data:
    - name: Sterling-Financial-AS
      asn: 65000
      description: Private ASN for the Sterling Financial EMEA MPLS backbone.
      organization: Sterling Financial
