---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: DcimDeviceType
  data:
    - name: NCS-540
      part_number: NCS-540-ACC-SYS
      height: 1
      manufacturer: Cisco
      platform: cisco_iosxr
    - name: MX204
      part_number: MX204-HW-BASE
      height: 1
      manufacturer: Juniper
      platform: juniper_junos