---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: DcimRoleGroupMapping
  data:
    # PE mappings
    - name: pe_arista_eos
      description: "Arista EOS PE devices"
      role: pe
      platform: arista_eos
      groups:
        edges:
          - node:
              name: pe_arista_eos
          - node:
              name: pes
    
    - name: pe_cisco_iosxr
      description: "Cisco IOS-XR PE devices"
      role: pe
      platform: cisco_iosxr
      groups:
        edges:
          - node:
              name: pe_cisco_iosxr
          - node:
              name: pes
    
    - name: pe_juniper_junos
      description: "Juniper Junos PE devices"
      role: pe
      platform: juniper_junos
      groups:
        edges:
          - node:
              name: pe_juniper_junos
          - node:
              name: pes
    
    - name: pe_nokia_sros
      description: "Nokia SR OS PE devices"
      role: pe
      platform: nokia_sros
      groups:
        edges:
          - node:
              name: pe_nokia_sros
          - node:
              name: pes
    
    # Core mappings
    - name: core_cisco_iosxr
      description: "Cisco IOS-XR Core devices"
      role: core
      platform: cisco_iosxr
      groups:
        edges:
          - node:
              name: core_cisco_iosxr
