---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: CoreRepository
  data:
    - name: infrahub-demo-sp
      location: "https://github.com/christoo-cisco/infrahub-demo-sp"
      default_branch: "main"
